### ISSUE TITLE
Option to disable extension

### ISSUE THREAD

**Issue by JLarky** [infi-pc/locatorjs#45]
Right now if I want to hide the locator I need to go to Chrome settings to disable it and enable it again. A simple turn-on/off button in the extension window would go a long way :)

**Comment by infi-pc** [comment]
I was thinking about something like this. 
Could you say why you personally need to disable it? @JLarky 

I have some hypotheses for general reasons: 
- The bottom left banner overlays something important
- Keyboard shortcut is used for something else on some projects
- ...
- Having multiple projects with different settings and on one of them it causes one of the previous issues 

I ask because I would put it into settings, but I don't know how to organize the settings.
The main thing is that I don't know how important could be to have different settings on each project (hostname:port). 
Or if it would be useful to have a keyboard shortcut for the disable/enable. 

I will be working on some setting improvement soon, so I can include it there.

**Comment by JLarky** [comment]
I would say the banner is the biggest issue :) but selection (alt+mousing over) itself is a bit too much sometimes :)

I think I'm just used to how devtool for elements or react work, where you have to go open devtool, go click on the "Select an element to inspect it" button in Elements or Components tabs. So I guess I wish there was a way to do that instead of it being turned on all the time :)

I would say for me what would have done it is just a quick way to completely turn it off and on again. But I can see the point of having it be more granular or configurable for different hosts:ports and stuff

**Comment by infi-pc** [comment]
thanks for the insight, so I have revised my plan

currently, I have released a new extension version - where I have completely removed the intro banner. 
The banner was originally there for the library version to teach all team members about this ability. In the extension, it is not necessary. 

- I plan to add a "close" button to the banner in Library version so everybody can close it - to don't show anymore.
- I am thinking of adding a context menu option - so it is possible to go to code just with a mouse.
- When having a context menu (or other option), I can add an option to disable the keyboard shortcut. 

I feel I should fix all the issues to prevent people from wanting to disable it. Mostly because I believe the alt(or anything)+click is the most convenient way and allows me to have this super fast workflow where I use it almost anytime I go to the editor :D 

Let me know if this plan is good for you or if you would still like to have the option to disable it :) 

Anyway, I will keep it open for a longer time if anybody else needs the disabling.

**Comment by JLarky** [comment]
That sounds fine :) I'm a big believer in having the option to disable stuff :) but not everyone agrees. Like when password managers get in the way of website UI and stuff :)

Yes, alt+click is a really cool and fast way to get to it :) but sometimes I just want to snooze the extension when I test something more advanced :) and I don't want to test the extension, I want to test the website (that's especially painful with lighthouse scores, profiling and stuff, so now everyone has to use incognito for that)

**Comment by infi-pc** [comment]
Hi, I was finally able to add project-specific settings that work both for the Extension and for the library version of Locator. And "disable" button included :) 

<img width="1250" alt="CleanShot 2022-09-30 at 12 14 49@2x" src="https://user-images.githubusercontent.com/2264725/193248641-fca30756-458b-4ad4-b966-97e6620709ac.png">

<img width="448" alt="CleanShot 2022-09-30 at 12 14 40@2x" src="https://user-images.githubusercontent.com/2264725/193248653-5c0062f9-b1c9-4078-a3d5-4f71e45bb96c.png">
