### ISSUE TITLE
bug:  Global editor link not working

### ISSUE THREAD

**Issue by fxOne** [infi-pc/locatorjs#94]
### Where the bug happens

- [X] Browser Extension
- [ ] Library
- [ ] Other

### your browser

Chrome 112.0.5571.0 

### Describe the bug

I have setup an editor link for all projects as you can see here:
![image](https://user-images.githubusercontent.com/5929640/216033287-48159c3a-e2f6-472d-81e8-0e6a0c0bf570.png)

I also use transform final link as you can see here:
![image](https://user-images.githubusercontent.com/5929640/216033522-31d66bc9-3d22-4ee5-8172-0b5fd57cd4ad.png)

As you can see in the link preview the global setting is missing. 

### To reproduce

Setup global setting. This are ignored in the link generation.

### Additional information

This function stopped working for me yesterday, so it might be related to this commit: https://github.com/infi-pc/locatorjs/commit/b2f7a6d9e12cfb6f2c814d6e3462ffd06be7c553

**Comment by infi-pc** [comment]
I think it will be because of this bugfix: https://github.com/infi-pc/locatorjs/commit/577122a9762374414c36929b3b35732f5e6fae46

correct behavior should be that the project setting overrides the global setting. You can clear the local config to get back the global config: 
![CleanShot 2023-02-02 at 15 51 02@2x](https://user-images.githubusercontent.com/2264725/216357875-b1a7c2d7-d2b3-4612-be4c-d3d73057570e.png)

**Comment by fxOne** [comment]
This fixed it for me, thanks!
